### PR TITLE
Add listener functionality

### PR DESCRIPTION
**Pull request by bdunn44**
I needed a way to respond to push events, so added a simple callback mechanism.

### CODE REVIEW

**Comment by bdunn44** [comment]
Hey @vinenoob / @vinenoobjelly any chance you can have a look at this?

**Comment by vinenoob** [comment]
Sorry @bdunn44 I've been a bit busy. I'll try to look at and approve it soon.

**Comment by bdunn44** [comment]
No worries! Just a friendly nudge. Thanks in advance!

**Comment by vinenoob** [comment]
Looks good to me. I'm going to wait to merge this until I remember how to upload to pypi again unless it's needed now

**Review by vinenoob — APPROVED** [review]

**Comment by bdunn44** [comment]
Thanks!

**Pull request merged**
