### PR TITLE
Quite a doozy

### PR DESCRIPTION
**Pull request by bdunn44**
This is one monster of a PR. Spent some time rewriting pretty much this whole module and made many major enhancements along the way. I'd recommend reading the example in the new readme to get a flavor for it before diving into the details.

- Created a fairly comprehensive suite of unit and integration tests with Pytest (see the new readme for how to run them) and added doc strings everywhere
- The controller now automatically retrieves reference data (zones and patterns) when it needs to, and returns cached data when it can
- The controller will now validate inputs before sending requests/commands (validation is run for zone names, pattern names, RGB values, and brightness values)
- All functions that interact with the controller now have an optional `timeout` argument to control how long to wait (vs. indefinitely waiting before). The `timeout` defaults to 10 seconds
- All command functions (setting light strings, colors, and patterns) now have a `sync` argument that controls whether to wait for a response from the controller before returning (defaults to `True`)
- The controller can now retrieve the state of multiple zones at once (vs. needing to send a separate request for each zone)
- Simplified the code that handles reading data from the web socket in the background by implementing a separate `WebSocketMonitor` class
- Implemented a much simplified model approach (in `model.py`) that eliminates the previous boilerplate code and inconsistency (e.g. some JSON objects were loaded into objects, others weren't).
    - JSON serialization & deserialization is now handled by helper functions in `helpers.py`
- Removed print statements in favor of Python's standard logging module (instead of setting the `True` flag when creating the controller you now simply set the log level to `DEBUG`)
- Implemented a custom `JellyFishException` that is raised by the module instead of `BaseException` (which many users may miss with their exception handling - I was one of them - because it is so low level)
- Renamed attributes and methods to adhere to Python norms (snake_case) and maintain consistency
    - The one exception to this is in `model.py`, where attributes align with the API (camelCase)
- Setting the light string now includes brightness control

There's at least one thing that may need to be cleaned up before merging... I can't figure out what a `-1` state means for a zone. I only see it after applying a light string, and sometimes the controller says the state is `3`, other times `-1`. See line 21 in `tests/integration/test_set_run_patterns.py` and line 47 in `jellyfishlightspy/model.py`. Would appreciate any light you can shed on that (pun intended).

It's a lot, I know! But I do think it's vastly improved. Let me know if you'd like to change anything.

### CODE REVIEW

**Comment by bdunn44** [comment]
@vinenoobjelly I just found the issues/comments in the API explorer repo where you describe how to save patterns, zones, and schedules. I should have a few hours to work on implementing that tomorrow and will add to this PR

**Comment by vinenoob** [comment]
@bdunn44 I'm seeing this and will get to looking at it in depth eventually. As for your questions about state, I'll see if I can answer them.
A "3" is documented in our code as a RUN_STATE_RUN_ONCE, which I typically for use when you want pretty direct and quick control, rather than it kinda auto running. We make use of it especially in our Zone Setup process. 

A -1 is being tougher for me to tell. It is called RUN_STATE_RUN_ONCE_STOP. Documentation is sparce on it, but it seems to mention that it may be a stop that doesn't turn off the power supply

**Comment by bdunn44** [comment]
Thanks for the info @vinenoob. Sounds like state 3 would be used when you're configuring a new soffit pattern, for example (when the active light blinks to show the current position). Still unclear on -1.... if the power supply is on that seems to indicate the zone is on, but "stop" makes it sound like it's off (does "stop" mean data is no longer being sent to the LEDs? Or maybe the data is static? Or maybe it's specifically for soffit patterns?). 

Like I said, the only time I've seen -1 is when retrieving the zone's state after applying a light string (using state 3), so that seems to imply -1 means the zone is on. After some practical testing that does seem to be the case - I ran the code below to check:

```python
from jellyfishlightspy import JellyFishController
import time

jfc = JellyFishController('my-controller')
jfc.connect()

lights = [(255, 0, 0), (0, 255, 0), (0, 0, 255)]
jfc.apply_light_string(lights, 100, ["Back lower"])

for i in range(5):
    state = jfc.get_zone_state("Back lower")
    pattern = state.file
    brightness = state.data.runData.brightness
    colors = state.data.colors
    print(f"Zone 'Back lower' is {state.state} (pattern: '{pattern}', colors: {colors}, brightness: {brightness})")
    time.sleep(2)

jfc.turn_off()
jfc.disconnect()
```

And here is the output:

```
Zone 'Back lower' is 3 (pattern: '', colors: [0, 0, 0, 255, 0, 0, 0, 255, 0, 0, 0, 255], brightness: 100)
Zone 'Back lower' is -1 (pattern: '', colors: [0, 0, 0, 255, 0, 0, 0, 255, 0, 0, 0, 255], brightness: 100)
Zone 'Back lower' is -1 (pattern: '', colors: [0, 0, 0, 255, 0, 0, 0, 255, 0, 0, 0, 255], brightness: 100)
Zone 'Back lower' is -1 (pattern: '', colors: [0, 0, 0, 255, 0, 0, 0, 255, 0, 0, 0, 255], brightness: 100)
Zone 'Back lower' is -1 (pattern: '', colors: [0, 0, 0, 255, 0, 0, 0, 255, 0, 0, 0, 255], brightness: 100)
```

If I run it multiple times, sometimes the first state is -1, so just seems to be a timing issue. But it does seem that after the light string is applied it switches to -1 and stays there. I visually checked and the lights do remain on throughout, so I think we can safely conclude -1 means "on" as far as this library is concerned.

Take your time with the review, I know it's a lot. I should also mention that if you think these changes are too wholesale just let me know - I can maintain a separate fork if need be.

**Comment by bdunn44** [comment]
@vinenoob I just pushed a commit that adds pattern configuration retrieval (i.e. getting `patternFileData`). Check it out! 

Up next will probably be the ability to apply any `PatternConfig` the user wants and create/update/delete patterns. What is the command for pattern removal, by the way? `toCtrlDel`? I can use Wireshark to find out if I don't hear from you.

**Comment by vinenoob** [comment]
I haven't tested the following, but I believe it to be right. 
The command to delete a pattern is as follows:
```json
{
  "cmd": "toCtlrSet",
  "patternFileDelete": {
    "file": "PatternFileNameHere",
    "folders": "FolderCategoryHere"
  }
}
```
Try not to get confused by folders being plural, it's not a spelling mistake on my part but how it is. "folders" is indeed a single string

**Comment by bdunn44** [comment]
Thanks @vinenoob. I can confirm that's correct. Just pushed a commit that adds the ability to create, update, and delete patterns.

**Comment by bdunn44** [comment]
@vinenoob just pushed a commit that adds getting, adding, and setting schedules (calendar and daily)!! 🙌🎉

In my testing I've noticed that the `MMDD` format doesn't fully work as I saw suggested in some comment somewhere. It seems the events get saved (because they show up when I do a get `scheduleData` request), but they aren't displayed in the app. `YYYYMMDD` works just fine.

I think the only thing left is adding and setting zones, and that should be real easy. Will be done adding new functionality soon unless there are more undocumented commands you can share - if so I'll be happy to implement them.

**Comment by bdunn44** [comment]
I'm about ready to drop the mic, @vinenoob 😄🎤 

Just pushed a commit that enables adding, deleting, and setting zone configurations. I added the get `hostName` command while I was at it. Took longer than I thought because the controller apparently has different JSON parsing logic for setting `zones` than for any other command I've tested... it wouldn't work unless there were no spaces in the JSON... 🤦‍♂️ It confused the heck out of me for a while, but it's working without issues now.

I think this library can now do basically everything the app can do... pretty cool! (except updating the firmware... I could probably implement that by sniffing the traffic to find the commands... I may implement that if I'm looking for another challenge)

**Comment by vinenoob** [comment]
I'm gonna try to take my time in reviewing this just to make sure I have some understanding of what is going on, but it all look fantastic at a glance. I have some hesitations moving away from the models I generated for the types/classes/json, but what you have seems pretty good. It seems likely I'll approve this as is. Sorry for not being the fastest on getting to this. One "missing" piece of the api you don't have is actually a command that tells you what the controller is planning to do in terms of scheduling, though of course there would be no reason for you to know of it as the app as of right now does not mention it.

**Comment by bdunn44** [comment]
No worries @vinenoob, take your time. I was sniffing traffic this weekend and found a few other things I'll look at implementing:

- `ctlrName` - getting/setting the controller's name.
- `timeConfig` - getting/setting timezone settings. 
- `http://x.x.x.x:8080/api/status` - always returns "Not upgrading" for me. Does this indicate whether a firmware update is in progress? If so what are the other possible return values? (my firmware is up-to-date so I can't test)
- `http://x.x.x.x:8080/api/v2/latest` - this seems to indicate whether a new firmware version is available (again, difficult for me to test since I'm up-to-date)

I'd also look at implementing the "next event" command (I assume that's what you mean by what the controller is planning to do), if you're open to sharing it.

**Comment by bdunn44** [comment]
Just added `ctlrName` (getting and setting) and `timeConfig` (just getting). I hesitate to add the ability to set `timeConfig` without knowing where the list of valid values is pulled from so we can validate input before sending to the controller. Can you point me to that reference data, @vinenoob?

I'll probably hold off on implementing `/api/v2/latest` and `/api/status` until I learn more about how those endpoints are intended to be used. Would be very cool to retrieve information on if an upgrade is available and what the latest version is - `jfc.firmware_version` contains an `isUpdate` attribute but that doesn't appear to be reliable.

A couple of other general questions...
- Is the controller's `hostName` (e.g. `JellyFish-780A.local`) guaranteed to be unique with in the local network?
- Either way, are there any other unique identifiers that could be retrieved from the controller (e.g. MAC address)?

**Comment by bdunn44** [comment]
> I have some hesitations moving away from the models I generated for the types/classes/json, but what you have seems pretty good.

Forgot to respond to this. It's definitely a different approach... What we had before was a lot of replicated boilerplate code (not surprising if the code was generated), and manual conversion to & from JSON. It works, but is difficult to understand, maintain, and extend. What we have now are very simple model classes (analogous to POJOs in the Java world) that leverage the JSON serialization and deserialization capabilities provided by Python out of the box (`json.dumps` and `json.loads`, respectively - see `helpers.py` for this logic). 

The one thing we have to be careful of there is typing - because Python is an untyped language we need some extra checking of the data that's being set in the objects. For example, a user could set a `"1"` value for an attribute that needs to be an `int`, which would produce invalid JSON. That's why there's explicit type checking for user-provided values before they are sent (I just moved these into a separate file, `validators.py`).

**Comment by bdunn44** [comment]
Hey @vinenoob, checking in. Have you had a chance to look at this?

**Comment by vinenoob** [comment]
@bdunn44  I'm very tempted to accept and pull this now, I just am not in a position to also update to pip right now. When I'm available to update pip I'll pull. This is just so I don't forget to update that later.

**Comment by bdunn44** [comment]
Sounds good! No rush. There's still some unimplemented API functionality we could look at adding in a future PR if you're interested. Just need some inside info on how the API works :)

>     * http://x.x.x.x:8080/api/status - always returns "Not upgrading" for me. Does this indicate whether a firmware update is in progress? If so what are the other possible return values? (my firmware is up-to-date so I can't test)
> 
>     * http://x.x.x.x:8080/api/v2/latest - this seems to indicate whether a new firmware version is available (again, difficult for me to test since I'm up-to-date)
> 
> 
> I'd also look at implementing the "next event" command (I assume that's what you mean by what the controller is planning to do), if you're open to sharing it.


> Just added `ctlrName` (getting and setting) and `timeConfig` (just getting). I hesitate to add the ability to set `timeConfig` without knowing where the list of valid values is pulled from so we can validate input before sending to the controller. Can you point me to that reference data, @vinenoob?
> 
> I'll probably hold off on implementing `/api/v2/latest` and `/api/status` until I learn more about how those endpoints are intended to be used. Would be very cool to retrieve information on if an upgrade is available and what the latest version is - `jfc.firmware_version` contains an `isUpdate` attribute but that doesn't appear to be reliable.
> 
> A couple of other general questions...
> 
>     * Is the controller's hostName (e.g. JellyFish-780A.local) guaranteed to be unique with in the local network?
> 
>     * Either way, are there any other unique identifiers that could be retrieved from the controller (e.g. MAC address)?

**Comment by vinenoob** [comment]
* Is the controller's hostName (e.g. JellyFish-780A.local) guaranteed to be unique with in the local network?

* Either way, are there any other unique identifiers that could be retrieved from the controller (e.g. MAC address)?

I don't believe any guarantees are made to ensure that the hostName is unique. That hostname is related to the mac address of the controller. However in a completely random world there is a 1/70,000 chance that 2 controllers have the same hostName, and due to the way we distribute controllers I believe the real world chances are much lower. If people name their controllers that can help create some unique identifying features, especially when combined with the hostName.

Take the following with a grain of salt, mainly interpreting from about a half hour of reading code.
For the timeConfig, for the timezone field, I _believe_ we use the [Posix.1 standard](https://support.cyberdata.net/portal/en/kb/articles/010d63c0cfce3676151e1f2d5442e311). It seems the "important" bits of the command are the lat/lon and the timezone. It seems timezone_name and loc_name are mostly decorative/ used to translate from text to numbers on the app.

**Comment by bdunn44** [comment]
Makes sense, thanks for the info. Based on that I probably won't add timezone update functionality. It's probably a super edge use case anyway.

Any insight into the firmware update API?

**Comment by vinenoob** [comment]
I'm gonna see about merging this (finally). Maybe make a issue for discussing the firmware update API so I can see about it later

**Pull request merged**
