### PR TITLE
Multiple improvments

### PR DESCRIPTION
**Pull request by bdunn44**
This PR adds the following:

1. Fixes issues with functions leaving data unread on the websocket which causes issues with subsequent data reads. For example:
```python
import jellyfishlightspy as jf

controller = jf.JellyFishController('my-controller.my-domain', True)
controller.connectAndGetData()
controller.playPattern('Special Effects/Red Waves')
controller.turnOff()
controller.getAndStoreZones()
```
```
...
Sending: {"cmd": "toCtlrGet", "get": [["zones"]]}
Recieved: {"cmd":"fromCtlr","runPattern":{"data":"","file":"Special Effects/Red Waves","id":"Back lower","state":1,"zoneName":["Back lower"]}}
Traceback (most recent call last):
  File "C:\Users\kbrys\Documents\Tech\Home Assistant Projects\Jellyfish Lighting\jellfishlights-py-test\test.py", line 8, in <module>
    controller.getAndStoreZones()
  File "C:\Python39\lib\site-packages\jellyfishlightspy\jellyfishmain.py", line 75, in getAndStoreZones
    zones = self.__getData(["zones"])
  File "C:\Python39\lib\site-packages\jellyfishlightspy\jellyfishmain.py", line 101, in __getData
    return json.loads(self.__recv())[data[0]]
KeyError: 'zones'
```
2. Adds more connection functionality (`connect()`, `disconnect()`, and `connected`)
3. Adds `sendColor()` which allows users to easily set an RGB color and brightness for one or more zones

I tested this pretty thoroughly with my installation. Happy to iterate on these changes as needed.

### CODE REVIEW

**Comment by vinenoob** [comment]
I'm looking and thinking about it. I think I'll approve it though I may want to do the versioning myself (setup.py). I may look into another way of dealing with messages hanging out in the websocket client but this would likely do for now.

**Comment by bdunn44** [comment]
Reverted the version change in d0d3d73

**Review by vinenoob — APPROVED** [review]
As said before, I think there is likely a better way to deal with the messages getting stuck in the websocket pipe. However this will work for now. Sorry for the wait and thanks for the contributions!

**Comment by bdunn44** [comment]
@vinenoob I totally agree, it feels pretty hacky right now. IMO the best solution would be to refactor the API to always respond with a single response per request. Seems that would make things more predictable and consistent. Even better, move to a true stateless http rest API!

Thanks for approving, this is a good step forward in the meantime

**Pull request merged**
